name: Deploy to EC2

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  EC2_IP: ${{ secrets.EC2_IP }}

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ecommerce-frontend .

      - name: Copy Docker Image to EC2
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          docker save ecommerce-frontend:latest | gzip > front-end-image.tar.gz
          scp -i id_rsa -o StrictHostKeyChecking=no front-end-image.tar.gz ec2-user@$EC2_IP:~/front-end-image.tar.gz
          rm id_rsa

      - name: Load and Run Docker Image on EC2
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -i $SSH_KEY -o StrictHostKeyChecking=no ec2-user@$EC2_IP << EOF
            docker load < ~/front-end-image.tar.gz
            docker run -d -p 80:4200 ecommerce-frontend:latest
          EOF
          rm id_rsa
